import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "../utility/font";

// Importing componets
import Navbar from "./components/Navbar/Navbar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<Navbar />
				<div className="max-w-5xl mx-auto px-10">{children}</div>
			</body>
		</html>
	);
}
